### ISSUE TITLE
Tweak the init methods of response_objects

### ISSUE THREAD

**Issue by NoHeDidnt** [Esterni/pyracing#54]
- For better uniformity the init methods of all (or most) response_objects should take the same arguments. With the exception of the classes in chart_data it is only a small tweak to get to: `def __init__(self, data):`

- We should read the information returned by iRacing like this: `self.laps = data.get('totalLaps')` instead of `self.laps = data['totalLaps']` just in case something is missing, changed its name or something like that. Also this would make it easy to set default values inside the get(), should we later want that.

**Comment by Esterni** [comment]
It also looks like iRacing sends an empty string `''` when a field has no value assigned. I only caught this after completing most of the documentation, so it will need another pass to determine what the value type is when there's an actual value assigned from iRacing

**Comment by XanderRiga** [comment]
Are there any fields we want to make sure we have? doing `.get()` is safer, because if we don't get a response we expect to it won't blow up, but are there fields we _want_ to blow up if we don't have? Like if we get a response from iracing that has nothing, we will send back an object and every single field will be `None`, I would say we want to blow up in that case or in the case we are missing a crucial part of the object we want to return, otherwise we can't guarantee any amount of data and the objects don't provide much value.

**Comment by NoHeDidnt** [comment]
I agree, we should implement a way to prevent empty or 'not enough filled' objects from being created or returned. This could be done inside the classes of  `response_objects` since they each have their own requirements.

There are also some smaller things in a few `client` methods, that don't go as planned when iracing returns an 'empty' response, that only contains placeholders like `"d": []` Here we could also handle some of the incorrect response data.

**Comment by Esterni** [comment]
We might not need to do anything.. but I’m not 100%. iRacing returns an empty string value when there is no value to be returned, which hasn’t posed a problem. The only issue that would arise is if iRacing stops sending a specific field entirely. 
current_seasons() is the only one so far that has the ability to return varying amounts of keys 
    	
    	

    	-Jacob
    
  




On Thu, Jul 30, 2020 at 3:25 PM -0700, "NoHeDidnt" <notifications@github.com> wrote:















I agree, we should implement a way to prevent empty or 'not enough filled' objects from being created or returned. This could be done inside the classes of  response_objects since they each have their own requirements.


There are also some smaller things in a few client methods, that don't go as planned when iracing returns an 'empty' response, that only contains placeholders like "d": [] Here we could also handle some of the incorrect response data.

**Comment by NoHeDidnt** [comment]
> For better uniformity the init methods of all (or most) response_objects should take the same arguments. With the exception of the classes in chart_data it is only a small tweak to get to: `def __init__(self, data):` 

#60 solved this

**Comment by Esterni** [comment]
Solved by #60 as referenced above. Instances of `dict` were changed to `data` and it was determined that .get() should not be used so that an exception will be raised in the event that iRacing changes the key values of the data returned to us.
